# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 21:46
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Sound Description')),
                ('src', models.FileField(default='settings.MEDIA_ROOT/example.mp3', storage=django.core.files.storage.FileSystemStorage('C:\\Users\\znxkz\\PycharmProjects\\dist\\media'), upload_to='user_sound')),
            ],
        ),
    ]
