# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 13:56
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0002_sound_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='src_ambient',
            field=models.FileField(default='settings.MEDIA_ROOT/example_ambient.wav', storage=django.core.files.storage.FileSystemStorage('C:\\Users\\znxkz\\PycharmProjects\\dist\\media'), upload_to='user_sound'),
        ),
        migrations.AddField(
            model_name='sound',
            name='src_primary',
            field=models.FileField(default='settings.MEDIA_ROOT/example_primary.wav', storage=django.core.files.storage.FileSystemStorage('C:\\Users\\znxkz\\PycharmProjects\\dist\\media'), upload_to='user_sound'),
        ),
    ]
